---
# binds k8s service account to role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksa-reader-binding
subjects:
- kind: ServiceAccount
  name: my-ksa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ksa-reader
  apiGroup: rbac.authorization.k8s.io
---
# role that defines permissions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksa-reader
rules:
# kubectl api-resources --namespaced=true
- apiGroups: [""]
  resources: ["namespaces","nodes", "pods", "secrets", "services", "configmaps","crontabs","persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"] # left out 'daemonsets' intentionally
  verbs: ["get", "list", "watch"]
---
# k8s service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-ksa
  namespace: default
