---
# binds k8s service account to role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksa-wi-reader-binding
subjects:
- kind: ServiceAccount
  name: my-wi-ksa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ksa-wi-reader
  apiGroup: rbac.authorization.k8s.io
---
# role that defines permissions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksa-wi-reader
rules:
- apiGroups: [""]
  resources: ["namespaces","nodes", "pods", "secrets", "services", "configmaps","crontabs","persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "replicasets", "statefulsets"] # intentionally left out 'deployments'
  verbs: ["get", "list", "watch"]
---
# k8s service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-wi-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: gcloud-user@${project_id}.iam.gserviceaccount.com
